<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8"/>
    <title>Upload Excel File</title>
    <link href='//fonts.googleapis.com/css?family=Lato:300' rel='stylesheet' type='text/css'>
    <style>
        body {
            margin: 50px 0 0 0;
            padding: 0;
            width: 100%;
            font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;
            text-align: center;
            color: #aaa;
            font-size: 18px;
        }

        h1 {
            color: #719e40;
            letter-spacing: -3px;
            font-family: 'Lato', sans-serif;
            font-size: 100px;
            font-weight: 200;
            margin-bottom: 0;
        }
    </style>
</head>
<body>
<div>Upload Excel File to complete locations</div>

    <form enctype="multipart/form-data" action="<?php echo 'http://dp2.digipeyk.com/services/location'// echo getUri(); ?>/upload/location-data" method="post">
        <input type="file" name="data">

        <input type="submit" name="submit" >
    </form>

</body>
</html>








